// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7TsmINyfaHXeRUVK-ZZWAEzDCC9egAbA',
    appId: '1:472434903041:web:e3d8c4dff1781ec6365800',
    messagingSenderId: '472434903041',
    projectId: 'todo-list-provider-281cd',
    authDomain: 'todo-list-provider-281cd.firebaseapp.com',
    storageBucket: 'todo-list-provider-281cd.appspot.com',
    measurementId: 'G-QSPEVKGPQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlqJ2Vkx4ZqR718Itfeeh6RjMkrg88PnU',
    appId: '1:472434903041:android:8b016984a71543c7365800',
    messagingSenderId: '472434903041',
    projectId: 'todo-list-provider-281cd',
    storageBucket: 'todo-list-provider-281cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmSxuarDnGdTvHEyuL1Wn2pDvZcNXoRBM',
    appId: '1:472434903041:ios:20b249331a151528365800',
    messagingSenderId: '472434903041',
    projectId: 'todo-list-provider-281cd',
    storageBucket: 'todo-list-provider-281cd.appspot.com',
    androidClientId: '472434903041-sr4fo1tcri7bpqtaf8l4pqctkrmocmb1.apps.googleusercontent.com',
    iosClientId: '472434903041-jj3ih10dg747lvp9tdkcpnd82ujl5gr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmSxuarDnGdTvHEyuL1Wn2pDvZcNXoRBM',
    appId: '1:472434903041:ios:20b249331a151528365800',
    messagingSenderId: '472434903041',
    projectId: 'todo-list-provider-281cd',
    storageBucket: 'todo-list-provider-281cd.appspot.com',
    androidClientId: '472434903041-sr4fo1tcri7bpqtaf8l4pqctkrmocmb1.apps.googleusercontent.com',
    iosClientId: '472434903041-jj3ih10dg747lvp9tdkcpnd82ujl5gr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );
}
